### ISSUE TITLE
set buy miner at specific price

### ISSUE THREAD

**Issue by ApexArtist** [alainsopp/powercostratio#2]
**Is your feature request related to a problem? Please describe.**
rollercoin do not provide buy order in market

**Describe the solution you'd like**
set buy at specific price.. to act like buy order

**Describe alternatives you've considered**
i think the script can loop and wait for specific prices

**Additional context**

**Comment by alainsopp** [comment]
Hi jonnytracker,

If I understand your request, you would like to specify a buy order price for a specific item, lets say 1.5 RLT, that will trigger a buy order as soon as the price of this item is going bellow 1.5 RLT ?

**Comment by ApexArtist** [comment]
Below would be great but even exact price is fine

**Comment by alainsopp** [comment]
Hi jonnytracker,
Unfortunetly I can't do something like this because it represents a violation of  "Terms of use" of the site (see section 1.10).
As a matter of fact, even using automated scripts like the one hosted in this repo, is also prohibited.
I hope you'll understand.
